# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: cvservice

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  layers: arn:aws:lambda:ap-southeast-1:940443069190:layer:request:2
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-southeast-1
  endpointType: REGIONAL
  iam:
    role: arn:aws:iam::940443069190:role/lambda-career-tutor-dev


functions:
  careertutor-cv-upload-service:
    name: careertutor-cv-upload
    handler: get_signed_url.lambda_handler
    description: get image signed url for s3 upload
    events:
      - http:
          path: /upload-cv
          method: get
          cors: true

  save-user-contact-information:
    name: save-user-contact-information
    handler: save_contact_us.lambda_handler
    description: save user feedback on dynamodb
    events:
      - http:
          path: /save-contact
          method: post
          cors: true

  send-email-service:
    name: send-email-notification
    handler: send_email.lambda_handler
    description: send email
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          maximumRetryAttempts: 3
          startingPosition: LATEST
          arn:
            Fn::GetAtt:
              - ContactUsTable
              - StreamArn

resources:
  Resources:
    ContactUsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: career-tutor-contact-us
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_IMAGE
