# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ mamun_wip ]
  pull_request:
    branches: [ mamun_wip ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: pre-commit/action@v2.0.3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Load config.py
      env:
        CONFIG_CONTENT: ${{ secrets.CONFIG_CONTENT }}
      run: |
          echo $CONFIG_CONTENT | base64 --decode > cvService/config.py
    - name: Lint with flake8
      run: pre-commit run --all-files
    - name: Test with pytest
      env:
        AWS_DEFAULT_REGION: ap-southeast-1
      run: |
        pytest
